# -*- coding: utf-8 -*-
"""Employee_Attrition_Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h-sKILl9wigcW4X-_0TFjul2JnYO5Mx8

**Importing Libraries / Dependencies**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

"""**Get the Data**"""

df = pd.read_csv('/content/Attrition data.csv')

"""**Data Exploration and Cleaning**"""

df.shape

df.head()

pd.set_option('display.max_columns',None)

df.head()

df.info()

# checking for null values
pd.isnull(df).sum()

# remove/ drop null values
df.dropna(inplace=True)

pd.isnull(df).sum()

# checking for duplicates
df.duplicated().value_counts()

# descriptive statistics
df.describe()

df.to_csv('clean_data.csv',index=False)